/* Copyright 2026 Armel F4HWN
 * Licensed under the Apache License, Version 2.0.
 *
 * BEAM overlay app.  Packet version 2 remains wire-compatible with the
 * resident implementation: one selected VFO is sent and a received VFO is
 * stored in the first free memory channel.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../app_api.h"
#include "beam_assets.h"   /* generated by gen_assets.py */

#define PACKET_MAGIC   0xBEA5u
#define PACKET_VERSION 2u
#define PACKET_START   0xABCDu
#define PACKET_END     0xDCBAu
#define PACKET_WORDS   36u
#define STORE_WORDS    18u   /* 72 bytes, 4-byte aligned for the payload */

enum {
    STATUS_READY = 0,
    STATUS_TX_WAIT,
    STATUS_TX_DONE,
    STATUS_RX_WAIT,
    STATUS_RX_SAVED,
    STATUS_RX_FULL,
    STATUS_ERROR,
};

typedef struct {
    uint16_t magic;
    uint8_t version;
    uint8_t pad;
    app_beam_channel_t channel;
} beam_payload_t;

_Static_assert(sizeof(beam_payload_t) == 48u,
               "BEAM v2 wire payload layout changed");

/* All the state in one struct: Thumb-1 code then reaches every field from a
 * single base address (one literal per function instead of one per global).
 * The packet buffer lives on app_main's stack, outside the 4 KiB overlay; the
 * overlay itself is zeroed by the loader at each launch. */
struct globals {
    uint8_t mode, status;
    bool receiving, running, dirty;
    uint16_t copiedChannel;
    const app_api_t *api;
    uint32_t *packet_store;   /* STORE_WORDS words, on app_main's stack */
};
static struct globals g;
#define A (g.api)

static uint16_t *packet(void) { return (uint16_t *)g.packet_store; }
static beam_payload_t *payload(void) { return (beam_payload_t *)&packet()[2]; }

static void clear_bytes(void *ptr, uint8_t count)
{
    uint8_t *p = (uint8_t *)ptr;
    while (count--) *p++ = 0;
}

static uint16_t crc16(const void *buffer, uint16_t size)
{
    const uint8_t *data = (const uint8_t *)buffer;
    uint16_t crc = 0;
    while (size--) {
        crc ^= (uint16_t)*data++ << 8;
        for (uint8_t bit = 0; bit < 8u; bit++)
            crc = (crc & 0x8000u) ? (uint16_t)((crc << 1) ^ 0x1021u)
                                  : (uint16_t)(crc << 1);
    }
    return crc;
}

static void obfuscate(void)
{
    uint16_t key[8];   /* obfuscation key, from the assets */
    uint16_t *p = packet();
    A->asset_read(OBFUSCATION, key, sizeof(key));
    for (uint8_t i = 0; i < 32u; i++)
        p[i + 1u] ^= key[i & 7u];
}

static void draw(void)
{
    /* T_STATE: READY in TX / RX mode, then one entry per later status. */
    char state[T_STATE_STRIDE];
    const uint8_t index = g.status ? (uint8_t)(g.status + 1u) : g.mode;
    A->asset_read(T_STATE + index * T_STATE_STRIDE, state, sizeof(state));
    A->beam_draw(state);
    A->blit_status();
    A->blit_full();
}

static void stop_rx(void)
{
    if (g.receiving) {
        A->beam_rx(false);
        g.receiving = false;
    }
}

static void send_packet(void)
{
    uint16_t *p = packet();
    clear_bytes(g.packet_store, STORE_WORDS * 4u);
    p[0] = PACKET_START;
    payload()->magic = PACKET_MAGIC;
    payload()->version = PACKET_VERSION;
    A->beam_get(&payload()->channel);
    p[34] = crc16(&p[1], 2u + 64u);
    p[35] = PACKET_END;
    obfuscate();

    g.status = STATUS_TX_WAIT;
    draw();
    A->beam_send(p);
    g.status = STATUS_TX_DONE;
    for (uint8_t i = 0; i < 3u; i++) {
        A->play_tone(880, 60);
        if (i < 2u) A->delay_ms(20);
    }
    g.dirty = true;
}

static void start(void)
{
    stop_rx();
    /* A channel save is committed only after app_main() returns.  Do not let a
       second RX overwrite that pending save; exit and relaunch to receive more. */
    if (g.mode && g.copiedChannel != 0xFFFFu)
        return;
    A->beam_prepare();
    if (!g.mode) {
        send_packet();
        return;
    }
    A->beam_rx(true);
    g.receiving = true;
    g.status = STATUS_RX_WAIT;
    g.dirty = true;
}

static bool valid_packet(void)
{
    uint16_t *p = packet();
    if (p[0] != PACKET_START || p[35] != PACKET_END)
        return false;
    obfuscate();
    if (p[34] != crc16(&p[1], 2u + 64u))
        return false;
    return payload()->magic == PACKET_MAGIC && payload()->version == PACKET_VERSION;
}

static void poll_rx(void)
{
    if (!g.receiving)
        return;
    const uint8_t result = A->beam_rx_poll(packet());
    if (result == APP_BEAM_RX_WAIT)
        return;
    if (result == APP_BEAM_RX_ERROR || !valid_packet()) {
        g.status = STATUS_ERROR;
        A->backlight_on();
        g.dirty = true;
        return;
    }

    g.copiedChannel = A->beam_save(&payload()->channel);
    A->beam_rx(false);
    g.receiving = false;
    g.status = g.copiedChannel == 0xFFFFu ? STATUS_RX_FULL : STATUS_RX_SAVED;
    A->backlight_on();
    g.dirty = true;
}

static void key_press(uint8_t key)
{
    switch (key) {
        case APP_KEY_UP:
        case APP_KEY_DOWN:
            stop_rx();
            g.mode ^= 1u;
            g.status = STATUS_READY;
            g.dirty = true;
            break;
        case APP_KEY_MENU:
            start();
            break;
        case APP_KEY_EXIT:
            g.running = false;
            break;
        case APP_KEY_PTT:
            break;
        default:
            A->play_tone(500, 60);
            break;
    }
}

__attribute__((section(".text.entry"), used))
void app_main(const app_api_t *api)
{
    uint32_t store[STORE_WORDS];   /* the packet: 4-byte aligned, not in the overlay */
    A = api;
    g.packet_store = store;
    /* TX mode, READY and not receiving: zeroed (.bss) */
    g.copiedChannel = 0xFFFFu;
    g.running = true;
    g.dirty = true;
    A->backlight_on();

    uint8_t previous = APP_KEY_INVALID;
    uint8_t batteryTicks = 0;
    while (g.running) {
        const uint8_t key = A->get_key();
        if (key == APP_KEY_SAVER) {
            previous = APP_KEY_INVALID;
        } else if (key == APP_KEY_WAKE) {
            previous = APP_KEY_INVALID;
            g.dirty = true;
        } else {
            if (key != previous && key != APP_KEY_INVALID) {
                A->backlight_on();
                key_press(key);
            }
            previous = key;
        }

        poll_rx();
        if (g.dirty) { draw(); g.dirty = false; }
        A->delay_ms(10);
        A->backlight_update();
        if (++batteryTicks >= 50u) {
            batteryTicks = 0;
            A->battery_sample();
            g.dirty = true;
        }
    }

    stop_rx();
    A->beam_leave();
}
