#!/usr/bin/env python3
"""Write every t001frames.py frame as a Flipper Zero Sub-GHz RAW file, plus an
index (README.md) with the values the decoder should show.

  t001flipper.py [out_dir]          (default: flipper/t001)

Same signal as flipper406.py: 433.650 MHz, 2-FSK, one burst per file (160 ms
carrier, 400 bps biphase). Send one file at a time, at least 2 s apart.
NEVER transmit these files on 406.0-406.1 MHz (distress band).
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from flipper406 import write_sub, FREQ
from t001frames import catalogue, fmt_pos

out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "flipper", "t001")
os.makedirs(out, exist_ok=True)
rows = []
for name, desc, frame, hid, pos, fine in catalogue():
    write_sub(os.path.join(out, name + ".sub"), frame)
    p = "none" if pos is None else fmt_pos(pos) + ("" if fine else " (coarse)")
    rows.append("| `%s.sub` | %s | `%s` | %s |" % (name, desc, hid, p))
with open(os.path.join(out, "README.md"), "w") as f:
    f.write("""# C/S T.001 test frames (Flipper Zero)

One `.sub` file per coding option of C/S T.001 Issue 4 Rev. 11 (October 2023),
Annex A, generated by `../../t001flipper.py` from `../../t001frames.py`
(%.3f MHz, 2-FSK, one burst per file). Copy the folder to `subghz/` on the
Flipper, set the radio to %.3f MHz FM wide, launch EPIRB 406, then Send one
file per burst, at least 2 s apart.

**Never transmit these files on 406.0-406.1 MHz (distress band).**

Positions: a test point (49.07624 N, 0.73018 E) and a south-west point
(33 52'08" S, 70 39'28" W). "coarse" = PDF-2 offsets absent or not applicable.
`../../t001check.py` runs the same frames through the host decoder.

| File | Coding option | 15-hex ID | Position |
|---|---|---|---|
""" % (FREQ / 1e6, FREQ / 1e6))
    f.write("\n".join(rows) + "\n")
print("%d files in %s" % (len(rows), out))
