#!/usr/bin/env python3
"""Write every t001frames.py frame as a LimeSDR IQ file (cs16: interleaved int16
I/Q, carrier at 0 Hz), for limetx.py / txall.py.

  t001lime.py [out_dir] [--mode psk|fsk|both] [--rate 1e6]     (default: t001/)

  psk  the real 406 beacon modulation: unmodulated carrier, then +/-1.1 rad
       biphase-L with ~150 us transitions (C/S T.001). The discriminator then
       outputs pulses, as with a real EPIRB: this is the one to test the app.
  fsk  the Flipper Zero signal (2-FSK, +/-2.38 kHz, same as test/flipper/t001):
       the discriminator outputs a square biphase.

One burst per file: 160 ms carrier, 112/144 bits at 400 bps, 20 ms tail
(about 1.8 MB short, 2.2 MB long at 1 MS/s; 61 files = 181 MB per mode, not in
git, regenerate them here). Also writes t001/README.md, the index txall.py reads.

NEVER transmit on 406.0-406.1 MHz (distress band); limetx.py refuses 405.9-406.2.
"""
import argparse, os, sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
from t001frames import catalogue, fmt_pos
from flipper406 import raw_durations, LEAD_US, TAIL_US, HALF_US

FSK_DEV = 2380.0     # FuriHalSubGhzPreset2FSKDev238Async
PSK_RAD = 1.1        # C/S T.001 modulation index
RISE_US = 150.0      # rise/fall time, T.001 limits 50-250 us
AMP = 0.7


def halves(frame_hex):
    """Biphase-L half-bit levels of the frame: 1 -> high, low; 0 -> low, high."""
    n = len(frame_hex) * 4
    v = int(frame_hex, 16)
    out = []
    for i in range(n):
        out += [1, 0] if (v >> (n - 1 - i)) & 1 else [0, 1]
    return out


def psk_iq(frame_hex, rate):
    half = int(round(HALF_US * 1e-6 * rate))
    ph = np.concatenate([
        np.zeros(int(LEAD_US * 1e-6 * rate)),
        np.repeat(np.where(np.array(halves(frame_hex)) == 1, PSK_RAD, -PSK_RAD), half),
        np.zeros(int(TAIL_US * 1e-6 * rate)),
    ])
    w = max(3, int(rate * RISE_US * 1e-6))
    win = np.hanning(w)
    ph = np.convolve(ph, win / win.sum(), mode="same")
    return AMP * np.exp(1j * ph)


def fsk_iq(frame_hex, rate):
    freq = np.concatenate([np.full(int(round(abs(d) * 1e-6 * rate)), FSK_DEV if d > 0 else -FSK_DEV)
                           for d in raw_durations(frame_hex)])
    return AMP * np.exp(1j * 2 * np.pi * np.cumsum(freq) / rate)


def write_cs16(path, iq):
    out = np.empty(2 * len(iq), dtype=np.int16)
    out[0::2] = np.round(iq.real * 32767)
    out[1::2] = np.round(iq.imag * 32767)
    out.tofile(path)


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("out", nargs="?", default=os.path.join(HERE, "t001"))
    p.add_argument("--mode", choices=["psk", "fsk", "both"], default="both")
    p.add_argument("--rate", type=float, default=1e6, help="sample rate (default 1e6)")
    a = p.parse_args()

    modes = ["psk", "fsk"] if a.mode == "both" else [a.mode]
    for m in modes:
        os.makedirs(os.path.join(a.out, m), exist_ok=True)
    rows = []
    cat = catalogue()
    for name, desc, frame, hid, pos, fine in cat:
        for m in modes:
            write_cs16(os.path.join(a.out, m, name + ".cs16"), (psk_iq if m == "psk" else fsk_iq)(frame, a.rate))
        p_ = "none" if pos is None else fmt_pos(pos) + ("" if fine else " (coarse)")
        rows.append("| `%s` | %s | `%s` | %s |" % (name, desc, hid, p_))
    with open(os.path.join(a.out, "README.md"), "w") as f:
        f.write("""# C/S T.001 test frames for LimeSDR

Generated by `../t001lime.py` from `../../t001frames.py` (same frames as the
Flipper files in `../../flipper/t001/`): cs16, %.0f S/s, carrier at 0 Hz, one
burst per file. `psk/` is the real beacon modulation (use this one), `fsk/` the
Flipper signal. The `.cs16` files are not in git: run `../t001lime.py` first.

**Never transmit on 406.0-406.1 MHz.** `limetx.py` refuses 405.9-406.2 MHz.

| File | Coding option | 15-hex ID | Position |
|---|---|---|---|
""" % a.rate)
        f.write("\n".join(rows) + "\n")
    print("%d frames x %s -> %s (cs16, %.0f S/s)" % (len(cat), "+".join(modes), a.out, a.rate))


if __name__ == "__main__":
    main()
