/* Copyright 2026 Armel F4HWN
 * https://github.com/armel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */

/*
 * Plasma — overlay app. A full-screen demoscene plasma on the 1-bit 128x64 LCD.
 * The scalar field sums four scrolled sines: horizontal (x), vertical (y),
 * diagonal (x+y) and a radial ripple around a slowly drifting centre. Because
 * (x-cx)^2 + (y-cy)^2 is separable, the whole field is still built from per-column
 * and per-row tables, so each of the 8192 pixels costs only a handful of adds.
 * Rendered either with an ordered 4x4 Bayer dither (stipple) or as sweeping bands.
 * Pure compute + framebuffer, no radio — it just works. The per-frame tables
 * live on app_main's stack (0.75 KiB kept out of the 4 KiB overlay) and no
 * division is linked.
 *
 * Keys: UP/DOWN speed · 1-5 pattern · STAR stipple/bands · F auto-cycle ·
 *       MENU pause · EXIT quit.
 */

#include <stdint.h>
#include <stdbool.h>
#include "../app_api.h"
#include "plasma_assets.h"   /* generated by gen_assets.py */

#define W 128
#define H 64

static const app_api_t *A;

/* The sine wave, the 4x4 ordered-dither matrix and the pattern presets are
 * read-only assets (gen_assets.py), copied onto app_main's stack at launch. */

__attribute__((section(".text.entry"), used))
void app_main(const app_api_t *api)
{
    A = api;
    A->backlight_on();
    A->status_clear();

    int8_t  sine[SIN_LEN];          /* 32 * sin(2*pi*i/256)                  */
    uint8_t bayer[BAYER_LEN];       /* idx = (y&3)*4 + (x&3), values 0..15   */
    uint8_t presets[NVAR][4];       /* x, y, diagonal scales, radial shift   */
    A->asset_read(SIN, sine, sizeof(sine));
    A->asset_read(BAYER, bayer, sizeof(bayer));
    A->asset_read(VAR, presets, sizeof(presets));

    /* Per-frame separable tables. */
    int8_t   colA[W];               /* horizontal sine, by column x */
    int8_t   rowA[H];               /* vertical sine, by row y       */
    int8_t   diagA[W + H];          /* diagonal sine, by (x + y)     */
    uint16_t sqx[W];                /* (x - cx)^2 for the radial term */
    uint16_t sqy[H];                /* (y - cy)^2                     */

    uint16_t t1 = 0, t2 = 0, t3 = 0, tr = 0, tc = 0, tc2 = 0;
    uint16_t autoCtr = 0;
    uint8_t  speed = 3;
    uint8_t  var   = 0;
    bool     bands = true;
    bool     autoc = false;
    bool     paused = false;
    bool     running = true;
    uint8_t  prevKey = APP_KEY_INVALID;

    while (running) {
        uint8_t key = A->get_key();
        if (key == APP_KEY_SAVER) {
            prevKey = APP_KEY_INVALID;
            A->delay_ms(10);
            A->backlight_update();
            continue;
        }
        if (key == APP_KEY_WAKE)
            key = APP_KEY_INVALID;
        if (key != prevKey && key != APP_KEY_INVALID) {
            A->backlight_on();
            switch (key) {
                case APP_KEY_EXIT: running = false; break;
                case APP_KEY_UP:
                case APP_KEY_DOWN: {
                    const int8_t direction = A->nav_dir(key);
                    if (direction > 0 && speed < 8u) speed++;
                    if (direction < 0 && speed > 1u) speed--;
                    break;
                }
                case APP_KEY_MENU: paused = !paused; break;
                case APP_KEY_STAR: bands = !bands; break;
                case APP_KEY_F:    autoc = !autoc; break;
                case APP_KEY_1: case APP_KEY_2: case APP_KEY_3:
                case APP_KEY_4: case APP_KEY_5:
                    var = (uint8_t)(key - APP_KEY_1); autoc = false; break;
                default: break;
            }
        }
        prevKey = key;
        if (!running)
            break;

        const uint8_t sx = presets[var][0], sy = presets[var][1];
        const uint8_t sd = presets[var][2], rsh = presets[var][3];

        /* drifting radial centre (gentle Lissajous), then the separable squares */
        const int cx = 64 + sine[(uint8_t)tc];        /* 32..96 */
        const int cy = 32 + (sine[(uint8_t)tc2] >> 1);/* 16..48 */

        for (uint8_t x = 0; x < W; x++) {
            colA[x] = sine[(uint8_t)(x * sx + t1)];
            int dx = (int)x - cx; sqx[x] = (uint16_t)(dx * dx);
        }
        for (uint8_t y = 0; y < H; y++) {
            rowA[y] = sine[(uint8_t)(y * sy + t2)];
            int dy = (int)y - cy; sqy[y] = (uint16_t)(dy * dy);
        }
        for (uint16_t s = 0; s < W + H; s++) diagA[s] = sine[(uint8_t)(s * sd + t3)];

        /* render all 8 pages: page 0 -> status line (top), pages 1..7 -> fb[0..6] */
        for (uint8_t x = 0; x < W; x++) {
            const int8_t  cxv = colA[x];
            const uint16_t sxv = sqx[x];
            const uint8_t bx  = x & 3u;
            for (uint8_t p = 0; p < 8u; p++) {
                uint8_t byte = 0;
                for (uint8_t b = 0; b < 8u; b++) {
                    const uint8_t y = (uint8_t)(p * 8u + b);
                    int v = cxv + rowA[y] + diagA[x + y]
                          + sine[(uint8_t)(((sxv + sqy[y]) >> rsh) + tr)];
                    v += 128;                                     /* 0..256 */
                    bool on;
                    if (bands) on = ((v >> 4) & 1u) != 0u;        /* sweeping stripes */
                    else {
                        int lvl = v >> 4; if (lvl > 15) lvl = 15;  /* 0..15 stipple */
                        on = lvl > (int)bayer[((y & 3u) << 2) | bx];
                    }
                    if (on) byte = (uint8_t)(byte | (1u << b));
                }
                if (p == 0) A->status_line[x] = byte;
                else        A->fb[p - 1][x]   = byte;
            }
        }
        A->blit_status();
        A->blit_full();

        if (!paused) {
            t1 += speed; t2 += (uint16_t)(speed + 1u); t3 += 1u;
            tr += speed; tc += 1u; tc2 += 2u;
            if (autoc && ++autoCtr >= 400u) {   /* next preset, wrapping without a modulo */
                autoCtr = 0;
                if (++var >= NVAR) var = 0;
            }
        }

        A->backlight_update();
    }
}
